# Generated by Django 5.2.4 on 2025-08-05 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('request', '0001_initial'),
        ('suppliers', '0002_alter_supplier_contact_person_alter_supplier_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поставки')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.PositiveIntegerField(default=0, verbose_name='Ожидаемое количество')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Фактически получено')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.delivery', verbose_name='Поставка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Товар')),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.requestitem', verbose_name='Связанная заявка')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
                'ordering': ['delivery', 'product'],
            },
        ),
    ]
