# Generated by Django 5.2.4 on 2025-08-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('unit', '0004_productunit_delivery_date_productunit_delivery_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='product',
        ),
        migrations.AddField(
            model_name='requestitem',
            name='product_unit',
            field=models.ForeignKey(default=2342342, on_delete=django.db.models.deletion.PROTECT, to='unit.productunit'),
            preserve_default=False,
        ),
    ]
