# Generated by Django 5.2.4 on 2025-08-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('create_empty', 'Создан пустым'), ('candidate_in_request', 'Кандидат на заявку'), ('in_request', 'В заявке'), ('in_request_cancelled', 'В заявке - отменен'), ('in_store', 'В магазине'), ('sold', 'Продан'), ('broken', 'Сломан'), ('lost', 'Утерян'), ('transferred', 'Передан'), ('extra_add_delivery', 'Экстренно вставлен в поставку')], default='create_empty', max_length=25, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_extra_add_delivery_item', models.BooleanField(default=False, verbose_name='Экстренная поставка (без заявки)')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Дата продажи')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Единица товара',
                'verbose_name_plural': 'Единицы товаров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='unit_produc_status_b2ed24_idx'), models.Index(fields=['serial_number'], name='unit_produc_serial__2d8df6_idx'), models.Index(fields=['sale_date'], name='unit_produc_sale_da_e3babf_idx')],
            },
        ),
    ]
