# Generated by Django 5.2.4 on 2025-08-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.requestitem', verbose_name='Позиция заявки'),
        ),
    ]
