# Generated by Django 5.2.4 on 2025-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_productunit_request_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('create_empty', 'Создан пустым'), ('candidate_in_request', 'Кандидат на заявку'), ('in_request', 'В заявке'), ('in_delivery', 'В поставке'), ('in_request_cancelled', 'В заявке - отменен'), ('in_store', 'В магазине'), ('sold', 'Продан'), ('broken', 'Сломан'), ('lost', 'Утерян'), ('transferred', 'Передан'), ('extra_add_delivery', 'Экстренно вставлен в поставку')], default='create_empty', max_length=25, verbose_name='Статус'),
        ),
    ]
