# Generated by Django 5.2.4 on 2025-08-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('unit', '0003_alter_productunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='delivery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryitem', verbose_name='Позиция поставки'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='store_arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
