# Generated by Django 5.2.4 on 2025-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0004_productunit_delivery_date_productunit_delivery_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
